package com.cdd.allpay;

public class Key {

  public static String key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmyjBftlifvEL60FuPtP1wPSFD47aK5Gmi2PTVESlP/pwiUaK4c8ol0SSH9OwFAMI3HPnslNIu7beRnevvXYjwTQTXtMRJ10hIuL5PwF3WdROJvciJMUaJmUgitxJIJwuljQIDMugDYPovOOVTfL3xmgo6ll9dfMbkocfiasBd6bUR4DC+gmYG+ZxJRmTnprhfIqCuPf8/OWWMN9jZv3fY+89ka2m/Emkp3uO/pBZPgznIomJhIKMFhZUFsM0o49B3umxIq3vw4q0CJQId5rjJpui4pUWxwjUAbkNVIZutiLtHfLDe+gSoLT7y4IeLwc2TGmTsvTl5BIzbhykoA5p3QIDAQAB";
}
